import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
const aspekta = localFont({
  src: "./fonts/Aspekta-600.ttf",
  weight: "600",
  style: "semibold",
  variable: "--font-aspekta",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${aspekta.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
